# .github/ISSUE_TEMPLATE/config.yml
blank_issues_enabled: false

contact_links:
  - name: "Questions & Support"
    url: https://github.com/TypNull/Tubifarry/discussions
    about: Ask questions or get help with Tubifarry in our Discussions forum.
  
  - name: "Documentation"
    url: https://github.com/TypNull/Tubifarry/wiki
    about: Check out the official documentation for Tubifarry.